pipeline {

  environment {
    HOME = '.'
  }

  options {
    ansiColor('xterm')
    withAWS(credentials:'AWS Access Key - Jenkins Service User - nwea-master')
  }

  agent { docker { image 'node:latest' } }

  triggers { cron('H H * * *') }

  stages {
    stage('Do AWS Inventory') {
      steps {
        script {
          def common = load "scripts/common.groovy"
          def creds_file_path = 'aws_creds'
          def creds_content = common.generateCredsFile()

          writeFile file: creds_file_path, text: creds_content
          sh """
            npm install
            cp -v patches/shared_ini_file_credentials.js node_modules/aws-sdk/lib/credentials/
            node .
          """
        }
      }
    }
  }
}
